version: '3.8'

services:

    inventory:
        build: ./inventory-service
        ports: 
            - 6969:6969
        environment:
            MONGODB_AUTH_DATABASE: admin
            MONGODB_HOST: mongodb-inventory
            MONGODB_PORT: 27017
            MONGODB_DATABASE: inventory
            MONGODB_USERNAME: root
            MONGODB_PASSWORD: root
        depends_on:
            - mongodb-inventory
        restart: always

    mongodb-inventory:
        build: ./mongodb-inventory
        environment:
            MONGO_INITDB_DATABASE: inventory
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
        restart: always
        
    # mongo-express-blue-door:
    #     image: mongo-express
    #     ports:
    #         - 8082:8082
    #     environment:
    #         VCAP_APP_PORT: 8082
    #         ME_CONFIG_MONGODB_SERVER: mongodb-blue-door
    #         ME_CONFIG_MONGODB_ADMINUSERNAME: root
    #         ME_CONFIG_MONGODB_ADMINPASSWORD: root
    #     depends_on:
    #         - mongodb-blue-door
    #     restart: always
